spring.application.name=FoodSwiper
server.port=8080
spring.datasource.url=jdbc:postgresql://34.182.87.140:5432/foodswiper-database
spring.datasource.username=postgres
spring.datasource.password=Project3
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
