DB_URL=jdbc:postgresql://34.182.87.140:5432/foodswiper-database
DB_USERNAME=postgres
DB_PASSWORD=Project3
DB_DDL_AUTO=update
DB_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

uGOOGLE_CLIENT_ID=replace-me
GOOGLE_CLIENT_SECRET=replace-me
GITHUB_CLIENT_ID=Ov23liX9sxRwuzIUFqCE
GITHUB_CLIENT_SECRET=ff8b118e05789ed73c6f7ce9b48e0987e6ca95a1
